### ISSUE TITLE
Better version of `atomize_map_keys/1` ...

### ISSUE THREAD

**Issue by nelsonic** [dwyl/useful#17]
Last night while googling I found: https://hex.pm/packages/atomic_map
It covers more cases is a single-function library:
https://github.com/ruby2elixir/atomic_map/blob/master/lib/atomic_map.ex
It didn't come up when we originally wrote ours ... 
Otherwise we would have used it!!

We could **either** 
include it as a dependency in this project and just proxy the function ...
***or*** 
borrow some of the code (with appropriate credit) to not have a dependency. 

What is _your_ preference?

**Comment by nelsonic** [comment]
Getting the following error while _using_[ **`AtomicMap`**](https://hex.pm/packages/atomic_map) in practice: 

```sh
     ** (ArgumentError) errors were found at the given arguments:

       * 1st argument: not an already existing atom

     code: assert Item.items_with_timers(1) > 0
     stacktrace:
       :erlang.binary_to_existing_atom("timer_id", :utf8)
       (atomic_map 0.9.3) lib/atomic_map.ex:53: AtomicMap.as_atom/3
       (atomic_map 0.9.3) lib/atomic_map.ex:21: anonymous fn/3 in AtomicMap.convert/2
       (stdlib 4.0) maps.erl:411: :maps.fold_1/3
       (elixir 1.13.4) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
       test/app_web/live/app_live_test.exs:31: (test)
```
hmm ... 🤷‍♂️ 
totally get why `:erlang.binary_to_existing_atom/2` would be invoked for this ... 👌 
but it leaves me/us in a pickle. 🤦‍♂️

**Comment by nelsonic** [comment]
"fixed" it by having the following line preceding: 
```elixir
assert Useful.typeof(:timer_id) == "atom"
```
But don't _like_ it ... 🙄

**Comment by nelsonic** [comment]
Ok. I feel like our `atomize_map_keys/1` is pretty decent now thanks to recent improvements e.g: #45 and #47

**Comment by nelsonic** [comment]
Closing. ✅
